// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6Cvk9T95Cl9AEHR4HunGPuIx0QmlC6g',
    appId: '1:273923021290:android:37326c5e5674ffa96a3a93',
    messagingSenderId: '273923021290',
    projectId: 'voicetask-2181a',
    storageBucket: 'voicetask-2181a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRJvC7tHffvhiGN-lWAdb1P8Z4P_GglY',
    appId: '1:273923021290:ios:5858afc2524a9e936a3a93',
    messagingSenderId: '273923021290',
    projectId: 'voicetask-2181a',
    storageBucket: 'voicetask-2181a.firebasestorage.app',
    androidClientId: '273923021290-so9e8ej2jpv5q750r6pot6qg777qa7he.apps.googleusercontent.com',
    iosClientId: '273923021290-ol17j3c8d2ddn8l3ls15hieii070n5aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.saytask',
  );

}